=== mebarki01011993abdelghani/m1_s2/XML/TP3/TP3/master.dtd
<!ENTITY  site1  "Luminy" 		>
<!ENTITY  site2  "St Jerome"	>
<!ENTITY  site3  "St Charles" 	>

<!ENTITY  adresseSitePerso      ".perso.luminy.univ-amu.fr/" >
<!ENTITY  http					"http://www."				 >
<!ENTITY  dom.luminy  			"univ-mrs.fr" 				 >
<!ENTITY  dom.dil     			"dil.&dom.luminy;" 			 >

<!ELEMENT master					((intervenant,enseignement,specialite,parcour)*)>
<!ELEMENT enseignement    			((nom,identifiant,nombreCreditResume,plan,lieu)*)>
<!ELEMENT intervenant				((identifiant,nom,mail,siteWeb)*)				 >
<!ELEMENT specialite				((nom,identifiant,code,finalite,lieu)*)			 >							 
<!ELEMENT parcour					((nom,responsable,debouche,description)*)		 >
<!ELEMENT semestre					(ue+)								   			 >																
<!ELEMENT ue						(((enseignements+),role)*)						 >
<!ELEMENT nom 						(#PCDATA)  >
<!ELEMENT responsable 				(#PCDATA)  >
<!ELEMENT debouche 					(#PCDATA)  >
<!ELEMENT description 				(#PCDATA)  >
<!ELEMENT role 						(Obligatoire|Facultatif)  >
<!ELEMENT lieu 						(#PCDATA)  >
<!ELEMENT code 						(#PCDATA)  >
<!ELEMENT finalite 					(#PCDATA)  >
<!ELEMENT plan 						(#PCDATA)  >
<!ELEMENT resume 					(#PCDATA)  >
<!ELEMENT nombreCredit 				(#PCDATA)  >
<!ELEMENT identifiant 				(#PCDATA)  >
<!ELEMENT mail 						(#PCDATA)  >
<!ELEMENT siteWeb 					(#PCDATA)  >
<!ATTLIST enseignement  id  IDREF  #IMPLIED>

=== mebarki01011993abdelghani/m1_s2/XML/TP3/TP3/master.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE master SYSTEM "master.dtd">


<master>
	<intervenant idIntervenant="massat">
		<identifiant>JLM</identifiant>
		<nom>Jean-Luc Massat</nom>
		<mail>jean-luc.massat@&dom.dil;</mail>
		<siteWeb>&http;jean-luc.massat&adresseSitePerso;</siteWeb>
	</intervenant>
	<intervenant idIntervenant="Santocanale">
		<identifiant>LS</identifiant>
		<nom>Luigi Santocanale</nom>
		<mail>luigi.santocanale@&dom.dil;</mail>
		<siteWeb>&http;luigi.santocanale&adresseSitePerso;</siteWeb>
	</intervenant>

	<enseignement idEnseignement="ENSINBU4">
		<nom>XML</nom>
		<identifiant>ENSINBU4</identifiant>
		<nombreCredit>3</nombreCredit>
		<resume>XML et les outils associés permettent de représenter et de manipuler des documents semi-structurés. Nous nous attachons, dans ce cours, à présenter les avantages d'XML dans le cadre du WEB et de la transmission des données en insistant sur la portabilité des documents et des applications.</resume>
		<plan>
				le langage XML et les DTD, les requêtes XPATH et le langage de transformation XSLT, l'utilisation de documents XML en Java, le langage des schémas XML.
		</plan>
		<lieu>&site1; &site2;</lieu>
	</enseignement>

	<specialite idSpecialite="GL">	
		<nom>Génie logiciel</nom>
		<identifiant>GL</identifiant>
		<code>GL</code>
		<finalite>Pro.</finalite>
		<lieu>&site3;</lieu>
	</specialite>
	<specialite idSpecialite="ID">	
		<nom>Informatique décisionnelle</nom>
		<identifiant>ID</identifiant>
		<code>FED</code>
		<finalite>Pro.</finalite>
		<lieu>&site1;</lieu>
	</specialite>
	
	<parcour idParcour="RO">
		<nom>Recherche opérationnelle</nom>
		<responsable>Yann VAXES</responsable>
		<debouche>Administrateur de bases de données ou d’entrepôts de données.</debouche>
		<debouche>Extraction, transformation et chargement des données.</debouche>
		<debouche>Études et développement informatique.</debouche>
		<description>
				ici description
		</description>
	</parcour>
	<semestre>
		<ue idUe ="master1">
			<cours>
						<lien ref="ENSINBU4"></lien>
						<lien ref="massat"></lien>
			</cours>
			<role>&obli;</role>
		</ue>			
	</semestre>
</master>
