=== mebarki01011993abdelghani/m1_s2/XML/PROJET/DTD/master.dtd
<!--ENTITY-->
<!ENTITY  site1  "UFR Sciences" 		        >
<!ENTITY  site2  "Université d'Aix-Marseille"	>
<!ENTITY  site3  "St Charles" 			        >
<!ENTITY  site4  "St Jerome" 			        >
<!ENTITY  adresseSitePerso      ".perso.luminy.univ-amu.fr/" >
<!ENTITY  http					"http://www."				 >
<!ENTITY  dom.amu				"univ-amu.fr"				 >
<!ENTITY  dom.lif				"lif.univ-mrs.fr"			 >
<!ENTITY  dom.luminy  			"univ-mrs.fr" 				 >
<!ENTITY  dom.dil     			"dil.&dom.luminy;" 			 >
<!ENTITY  obli     				"Obligatoire" 			     >
<!ENTITY  falc     				"Falcultatif" 			     >
<!ENTITY  cred3     			"3" 			     		 >
<!ENTITY  cred6     			"6" 			     		 >
<!ENTITY  noResume				"Nous sommes désolé, mais nous n'avons pas encore de résumé.">

<!--RELATIONS ELEMENTS-->
<!ELEMENT master					(intervenants,enseignements,blocks,semestres,specialites,parcours,description)>
<!ELEMENT enseignement    			(nom,identifiant,nombreCredit,professeurs?,resume,pre-requis?,plan?,etablissement*,ref-intervenant*,adresse*,autre?)>
<!ELEMENT intervenant				(identifiant,nom,mail*,siteWeb?,telephone*,adresse?,etablissement,autre?)>
<!ELEMENT specialite				(nom,identifiant,code,finalite?,etablissement+,responsable,description,competences,connaissances?,ref-semestre*,politiqueDesStages,aspects?,modalites?,conditionAdmission,debouches?,poursuitesEtudes?)>							 
<!ELEMENT parcour					(nom,ref-specialite+,autre*)>
<!ELEMENT block 					(ref-enseignement+)>		
<!ELEMENT blocks 					(block+)>						
<!ELEMENT semestre					(ref-block+)>	
<!ELEMENT responsable 				(ref-intervenant+)>
<!ELEMENT parcours 					(parcour*)>
<!ELEMENT semestres					(semestre*)>
<!ELEMENT intervenants        		(intervenant)*>
<!ELEMENT enseignements        		(enseignement)*>
<!ELEMENT specialites        		(specialite)*>
<!ELEMENT professeurs        		(ref-intervenant+)>

<!--ELEMENTS-->
<!ELEMENT pre-requis					(#PCDATA | p)*>
<!ELEMENT aspects						(#PCDATA | p)*>
<!ELEMENT modalites						(#PCDATA | p)*>
<!ELEMENT politiqueDesStages			(#PCDATA | p)*>
<!ELEMENT conditionAdmission 			(#PCDATA | p)*>
<!ELEMENT poursuitesEtudes				(#PCDATA | p)*>
<!ELEMENT nom 						    (#PCDATA)>
<!ELEMENT debouches					    (#PCDATA | p)*>
<!ELEMENT description 					(#PCDATA | p)*>
<!ELEMENT etablissement 				(#PCDATA)>
<!ELEMENT code 						    (#PCDATA)>
<!ELEMENT finalite 					    (#PCDATA)>
<!ELEMENT plan 						    (#PCDATA)>
<!ELEMENT resume 					    (#PCDATA | p)*>
<!ELEMENT nombreCredit 					(#PCDATA)>
<!ELEMENT identifiant 					(#PCDATA)>
<!ELEMENT mail 						    (#PCDATA)>
<!ELEMENT siteWeb 					    (#PCDATA)>
<!ELEMENT ref-intervenant    			(#PCDATA)>
<!ELEMENT ref-enseignement   			(#PCDATA)>
<!ELEMENT ref-specialite	   			(#PCDATA)>
<!ELEMENT ref-semestre   				(#PCDATA)>
<!ELEMENT connaissances      			(#PCDATA | p)*>
<!ELEMENT competences        			(#PCDATA | p)*>
<!ELEMENT telephone        				(#PCDATA)>
<!ELEMENT adresse        				(#PCDATA)>
<!ELEMENT titre        					(#PCDATA)*>

<!-- Permet de créer un element adapter à son besoin -->
<!ELEMENT autre        					(titre, p, ANY*)>

<!--HTML BALISE -->
<!ELEMENT p							(#PCDATA| em | ul | strong | table | p)*  >				
<!ELEMENT strong					(#PCDATA|p)*>				
<!ELEMENT em						(#PCDATA)>
<!ELEMENT ul						(li+ | p)*>
<!ELEMENT li						(#PCDATA|p|ul|table)*>
<!ELEMENT table						(tr+)>
<!ELEMENT tr						(th+|d+)>
<!ELEMENT th						(#PCDATA)>
<!ELEMENT ref-block					(#PCDATA)>

<!--ATTRIBUTS-->
<!ATTLIST enseignement  idEnseignement  ID  #REQUIRED>
<!ATTLIST intervenant  idIntervenant  ID  #REQUIRED>
<!ATTLIST specialite  idSpecialite  ID  #REQUIRED>
<!ATTLIST parcour  idParcour  ID  #REQUIRED>
<!ATTLIST semestre  idSemestre  ID  #REQUIRED>
<!ATTLIST block  idBlock  ID  #REQUIRED>
<!ATTLIST ref-intervenant  ref IDREF  #REQUIRED>
<!ATTLIST ref-enseignement  ref IDREF  #REQUIRED>
<!ATTLIST ref-specialite  ref IDREF  #REQUIRED>
<!ATTLIST ref-semestre  ref IDREF  #REQUIRED>
<!ATTLIST ref-block  ref IDREF  #REQUIRED>
<!ATTLIST block  etat  (Obligatoire|Falcultatif)  #REQUIRED>
<!ATTLIST block  titre CDATA   #REQUIRED>

=== mebarki01011993abdelghani/m1_s2/XML/PROJET/XML/master.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE master SYSTEM "../DTD/master.dtd">
<?xml-stylesheet type="text/xsl" href="master.xsl" ?>

<master>
    <intervenants>
        <intervenant idIntervenant="IN18">
            <identifiant>IN18</identifiant>
            <nom>Jean-Luc MASSAT</nom>
            <mail>jean-luc.massat&dom.amu;</mail>
            <telephone>0491829482</telephone>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="IN7680">
            <identifiant>IN7680</identifiant>
            <nom>Claude LAI</nom>
            <mail>Claude LAI@&dom.amu;</mail>
            <telephone>04 91 82 93 16</telephone>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="IN3524">
            <identifiant>IN3524</identifiant>
            <nom>Denis LUGIEZ</nom>
            <mail>denis.luigiezZ@&dom.amu;</mail>
            <telephone>0413551333</telephone>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="IN17708">
            <identifiant>IN17708</identifiant>
            <nom>Stephane MICHEL</nom>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="IN9224">
            <identifiant>IN9224</identifiant>
            <nom>Remi MORIN</nom>
            <mail>remi.morin@&dom.amu;</mail>
            <telephone>0491829394</telephone>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="IN7722">
            <identifiant>IN7722</identifiant>
            <nom>Noel NOVELLI</nom>
            <mail>noel.noveli@&dom.amu;</mail>
            <telephone>04 91 82 93 70</telephone>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="IN13794">
            <identifiant>IN13794</identifiant>
            <nom>Frederic OLIVE</nom>
            <mail>frederic.olive@&dom.amu;</mail>
            <telephone>0491829000</telephone>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="IN12632">
            <identifiant>IN12632</identifiant>
            <nom>Nicola OLIVETTI</nom>
            <mail>nicolas.olivetti@&dom.amu;</mail>
            <telephone> 04 860 91 046</telephone>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="IN12969">
            <identifiant>IN12969</identifiant>
            <nom>Lydie RENE CHABAROT</nom>
            <mail>lydie.rene@&dom.amu;</mail>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="IN4595">
            <identifiant>IN4595</identifiant>
            <nom>Pierre-Alain REYNIER</nom>
            <mail> pierre-alain.reynier@&dom.amu;</mail>
            <telephone>04 91 82 93 13</telephone>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="IN7931">
            <identifiant>IN7931</identifiant>
            <nom>Sylvie RISCH</nom>
            <mail>sylvie.risch@&dom.amu;</mail>
            <telephone>0491829316</telephone>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="IN26">
            <identifiant>IN26</identifiant>
            <nom>Claude SABATIER</nom>
            <mail>claude.sabatier@&dom.amu;</mail>
            <telephone>04 91 82 94 81</telephone>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="IN16625">
            <identifiant>IN16625</identifiant>
            <nom>Sana SELLAMI</nom>
            <mail>sana.sellami@&dom.amu;</mail>
            <telephone>+33 4 91 05 60 57</telephone>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="IN8086">
            <identifiant>IN8086</identifiant>
            <nom>Yann VAXES</nom>
            <mail> yann.vaxes@&dom.amu;</mail>
            <telephone>0491829196</telephone>
            <etablissement>&site1;, &site2;</etablissement>
        </intervenant>
        <intervenant idIntervenant="II1000">
            <identifiant>II1000</identifiant>
            <nom>Thierry ARTIÈRES</nom>
            <mail>Thierry.artieres@&dom.lif;</mail>
            <etablissement>École Centrale Marseille</etablissement>
        </intervenant>

        <intervenant idIntervenant="IN616">
            <identifiant>II1000</identifiant>
            <nom>Roland AGOPIAN</nom>
            <mail>roland.agopian@&dom.amu;</mail>
            <telephone>0413551364</telephone>
            <etablissement>UFR Sciences</etablissement>
        </intervenant>

        <intervenant idIntervenant="IN1021">
            <identifiant>IN1021</identifiant>
            <nom>clara BERTOLISSI</nom>
            <mail>clara.bertolissi@&dom.amu;</mail>
            <telephone>04 91 82 95 27</telephone>
            <etablissement>UFR Science</etablissement>
        </intervenant>

        <intervenant idIntervenant="IN2563">
            <identifiant>IN2563</identifiant>
            <nom>Emmanuel GODARD</nom>
            <mail>emmanuel.godard@&dom.amu;</mail>
            <telephone></telephone>
            <etablissement>UFR Science</etablissement>
        </intervenant>

        <intervenant idIntervenant="IN6213">
            <identifiant>IN6213</identifiant>
            <nom>Arnaud LABOUREL</nom>
            <mail>arnaud.labourel@&dom.amu;</mail>
            <telephone>0491829195</telephone>
            <etablissement>UFR Science</etablissement>
        </intervenant>

        <intervenant idIntervenant="IN7001">
            <identifiant>IN7001</identifiant>
            <nom>Nadia CREIGNOU</nom>
            <mail>nadia.creignou@&dom.amu;</mail>
            <telephone>04 91 82 94 80</telephone>
            <etablissement>UFR Science</etablissement>
        </intervenant>

        <intervenant idIntervenant="IN8007">
            <identifiant>IN8007</identifiant>
            <nom>Line JAMET</nom>
            <mail>line.jakubiec@&dom.amu;</mail>
            <telephone>0491829311</telephone>
            <etablissement>UFR Science</etablissement>
        </intervenant>

        <intervenant idIntervenant="IN8615">
            <identifiant>IN8615</identifiant>
            <nom>Bertrand ESTELLON</nom>
            <mail>bertrand.estellon@&dom.amu;</mail>
            <telephone> 04 91 82 94 92</telephone>
            <etablissement>UFR Science</etablissement>
        </intervenant>

        <intervenant idIntervenant="IN9941">
            <identifiant>IN9941</identifiant>
            <nom>Frederic BECHET</nom>
            <mail>frederic.bechet@&dom.amu;</mail>
            <telephone>04 91 82 95 59</telephone>
            <etablissement>UFR Science</etablissement>
        </intervenant>

        <intervenant idIntervenant="IN10388">
            <identifiant>IN10388</identifiant>
            <nom>Benoit FAVRE</nom>
            <mail>benoit.favre@&dom.amu;</mail>
            <telephone></telephone>
            <etablissement>UFR Science</etablissement>
        </intervenant>

        <intervenant idIntervenant="IN12068">
            <identifiant>IN12068</identifiant>
            <nom>Djamal HABET</nom>
            <mail>djamal.habet@&dom.amu;</mail>
            <telephone> 0491288321</telephone>
            <etablissement>UFR Science</etablissement>
        </intervenant>

        <intervenant idIntervenant="IN12316">
            <identifiant>IN12316</identifiant>
            <nom>Isabelle DEMONGODIN</nom>
            <mail>isabel.demongodin@&dom.amu;</mail>
            <telephone>0491056077</telephone>
            <etablissement>UFR Science</etablissement>
        </intervenant>

        <intervenant idIntervenant="IN12544">
            <identifiant>IN12544</identifiant>
            <nom>Omar BOUCELMA</nom>
            <mail>omar.boucelma@&dom.amu;</mail>
            <telephone>0491056053</telephone>
            <etablissement>UFR Science</etablissement>
        </intervenant>


        <intervenant idIntervenant="IN14758">
            <identifiant>IN14758</identifiant>
            <nom>Martine BROCHE</nom>
            <mail>martine.broche@&dom.amu;</mail>
            <etablissement>UFR Science</etablissement>
        </intervenant>
    </intervenants>
    <enseignements>
        <enseignement idEnseignement="ENSINBU1">
            <nom>ANGLAIS</nom>
            <identifiant>ENSINBU1</identifiant>
            <nombreCredit>&cred3;</nombreCredit>
            <resume>
                Apprendre l'anglais
            </resume>
	
        </enseignement>
        <enseignement idEnseignement="ENSINBU2">
            <nom>COMMUNICATION</nom>
            <identifiant>ENSINBU2</identifiant>
            <nombreCredit>&cred3;</nombreCredit>
            <resume>
                <p>chapitre 1  : Théories de la communication : 1.1 La théorie mathématique de l’information (Shannon, Weaver), la cybernétique (Wiener)</p>
                <p> 1.2 La théorie de Palo Alto ( Bateson, Watzlawick) et la théorie de la communication par les processus (Mucchielli)</p>
                <p>chapitre 2 : Rôle de l’interculturalité dans le travail en équipe : 2.1 L’enquête interculturelle de Hofstede pour IBM 2.2 La gestuelle et le paralangage et la proxémie dans le monde (Hall) </p>
                <p>chapitre 3 : Notions de management et de travail collaboratif 3.1 Le travail collaboratif vs le travail coopératif 3.2 La notion de groupes 3.3 Les compétences managériales</p>
            </resume>
            <pre-requis>Particulièrement utile pour un choix d’options, les échanges internationaux et la formation continue.</pre-requis>
        </enseignement>
